import { PDFDocument, PDFFont, PDFPage, StandardFonts, rgb } from "pdf-lib";
import type { Color as PdfColor } from "pdf-lib";
import type { Action } from "@/lib/types";
import { linesFor, money } from "@/components/resolve/rollup";
import { OBSERVED_EXPOSED } from "@/lib/data/actions";
import { OWNERSHIP_THRESHOLD_NOTE } from "@/lib/data/bom";
import { CUSTOMER } from "@/lib/data/customer";
import { DOC_TITLE, DOC_INTRO, DOC_META, ISSUE_DATE, ISSUER } from "@/lib/documents/content";
import {
  deriveLineItems,
  deriveAffiliateRows,
  affiliateSourceIds,
  dollars,
  type LineItemRow,
  type AffiliateRow,
} from "@/lib/documents/derive";
import { wrapText, truncateToWidth, sanitizeForPdf } from "@/lib/documents/text";

// ------------------------------------------------------------------
// Real vector PDF export for the four RESOLVE documents, built with
// pdf-lib (programmatic, no headless browser -- Vercel-function safe)
// against the Courier standard fonts, so every render is selectable
// text, not a rasterized screenshot.
//
// Every figure drawn here comes from lib/documents/derive.ts, the
// same derivation components/resolve/DocumentModal.tsx reads for the
// on-screen preview. Nothing is authored into the PDF a second time.
// ------------------------------------------------------------------

const PAGE_W = 612; // US Letter, points
const PAGE_H = 792;
const MARGIN = 50;
const CONTENT_W = PAGE_W - MARGIN * 2;
const FOOTER_H = 40;

const COLOR = {
  ink: rgb(0.1, 0.11, 0.13),
  secondary: rgb(0.35, 0.37, 0.41),
  dim: rgb(0.55, 0.57, 0.61),
  rule: rgb(0.82, 0.83, 0.86),
  ruleStrong: rgb(0.6, 0.62, 0.66),
  critical: rgb(0.72, 0.2, 0.27), // matches --critical
  focus: rgb(0.58, 0.45, 0.14), // matches --focus, darkened for print contrast
  modeled: rgb(0.4, 0.34, 0.6), // matches --modeled -- reserved for MODELED data only
  white: rgb(1, 1, 1),
};

const DISCLAIMER =
  "REPRESENTATIVE DATA / FICTIONAL SCENARIO. Generated by Gallium for product demonstration only. Not a real filing, shipment, purchase, or transaction.";

// ---- low-level page writer ----------------------------------------

class Writer {
  doc: PDFDocument;
  font: PDFFont;
  bold: PDFFont;
  page!: PDFPage;
  y = 0;

  constructor(doc: PDFDocument, font: PDFFont, bold: PDFFont) {
    this.doc = doc;
    this.font = font;
    this.bold = bold;
  }

  newPage() {
    this.page = this.doc.addPage([PAGE_W, PAGE_H]);
    this.page.drawRectangle({ x: 0, y: 0, width: PAGE_W, height: PAGE_H, color: COLOR.white });
    this.y = PAGE_H - MARGIN;
  }

  /** Start a new page if the next block would land in the footer band. */
  ensure(h: number) {
    if (this.y - h < MARGIN + FOOTER_H) this.newPage();
  }

  private draw(str: string, x: number, size: number, font: PDFFont, color: PdfColor) {
    this.page.drawText(sanitizeForPdf(str), { x, y: this.y, size, font, color });
  }

  textL(str: string, size: number, color: PdfColor = COLOR.ink, font: PDFFont = this.font) {
    this.draw(str, MARGIN, size, font, color);
  }

  /** Right-aligned text ending at `rightX` (defaults to the page's right margin). */
  textR(str: string, size: number, color: PdfColor = COLOR.ink, font: PDFFont = this.font, rightX = PAGE_W - MARGIN) {
    const clean = sanitizeForPdf(str);
    const w = font.widthOfTextAtSize(clean, size);
    this.draw(str, rightX - w, size, font, color);
  }

  /** Left-aligned text starting at an arbitrary x. */
  textAt(str: string, x: number, size: number, color: PdfColor = COLOR.ink, font: PDFFont = this.font) {
    this.draw(str, x, size, font, color);
  }

  row(left: string, right: string, size = 9, color: PdfColor = COLOR.ink, font: PDFFont = this.font) {
    this.textL(left, size, color, font);
    this.textR(right, size, color, font);
  }

  hr(strong = false) {
    this.page.drawLine({
      start: { x: MARGIN, y: this.y },
      end: { x: PAGE_W - MARGIN, y: this.y },
      thickness: strong ? 1 : 0.5,
      color: strong ? COLOR.ruleStrong : COLOR.rule,
    });
  }

  down(h: number) {
    this.y -= h;
  }

  sectionLabel(label: string, corner?: string) {
    this.ensure(24);
    this.down(4);
    this.row(label.toUpperCase(), corner ?? "", 8, COLOR.dim, this.bold);
    this.down(4);
    this.hr(true);
    this.down(12);
  }

  /** A key/value row with a hairline underneath, matching the on-screen Field. */
  field(k: string, v: string, valueColor: PdfColor = COLOR.ink) {
    this.ensure(18);
    this.textL(k, 8.5, COLOR.secondary, this.font);
    this.textR(v, 8.5, valueColor, this.font);
    this.down(5);
    this.hr();
    this.down(11);
  }

  paragraph(text: string, size = 9, color: PdfColor = COLOR.secondary, maxWidth = CONTENT_W) {
    for (const line of wrapText(this.font, size, text, maxWidth)) {
      this.ensure(size + 4);
      this.textL(line, size, color);
      this.down(size + 5);
    }
  }
}

// ---- table renderers ------------------------------------------------

const COL_MPN_W = 85;
const COL_DESC_W = 220;
const COL_QTY_W = 40;
const COL_LEAD_W = 42;
const COL_UNIT_W = 58;

function tableCols() {
  const mpn = MARGIN;
  const desc = mpn + COL_MPN_W;
  const qtyR = desc + COL_DESC_W + COL_QTY_W;
  const leadR = qtyR + COL_LEAD_W;
  const unitR = leadR + COL_UNIT_W;
  const extR = PAGE_W - MARGIN;
  return { mpn, desc, qtyR, leadR, unitR, extR, descW: COL_DESC_W };
}

function drawLineItemTable(w: Writer, action: Action, rows: LineItemRow[], subtotal: number, units: number | null, extendedTotal: number | null) {
  const c = tableCols();
  w.ensure(20);
  w.textAt("MPN", c.mpn, 7.5, COLOR.dim, w.bold);
  w.textAt("DESCRIPTION", c.desc, 7.5, COLOR.dim, w.bold);
  w.textR("QTY/U", 7.5, COLOR.dim, w.bold, c.qtyR);
  w.textR("LEAD", 7.5, COLOR.dim, w.bold, c.leadR);
  w.textR("UNIT $", 7.5, COLOR.dim, w.bold, c.unitR);
  w.textR("EXT $", 7.5, COLOR.dim, w.bold, c.extR);
  w.down(4);
  w.hr(true);
  w.down(11);

  for (const r of rows) {
    w.ensure(16);
    const desc = truncateToWidth(w.font, 7.5, `${r.description}`, c.descW - 6);
    w.textAt(r.mpn, c.mpn, 7.5, COLOR.ink);
    w.textAt(desc, c.desc, 7.5, COLOR.secondary);
    w.textR(String(r.qtyPerUnit), 7.5, COLOR.secondary, w.font, c.qtyR);
    w.textR(`${r.leadTimeWeeks}W`, 7.5, COLOR.secondary, w.font, c.leadR);
    w.textR(`$${r.unitCost.toFixed(2)}`, 7.5, COLOR.secondary, w.font, c.unitR);
    w.textR(`$${r.ext.toFixed(2)}`, 7.5, COLOR.ink, w.font, c.extR);
    w.down(4);
    w.hr();
    w.down(10);
  }

  w.ensure(16);
  w.row(`PER-UNIT BOM VALUE / ${rows.length} LINES`, dollars(subtotal), 8.5, COLOR.ink, w.bold);
  w.down(13);
  if (units && extendedTotal) {
    w.ensure(16);
    w.row(`EXTENDED / ${units.toLocaleString("en-US")} UNITS`, money(extendedTotal), 8.5, COLOR.focus, w.bold);
    w.down(13);
  }
}

function drawAffiliatesTable(w: Writer, action: Action, rows: AffiliateRow[]) {
  w.paragraph(
    `RED FLAG 29 DILIGENCE / AFFILIATES SCREENING / OBLIGATION ATTACHES ${OWNERSHIP_THRESHOLD_NOTE.redFlag29 === "required" ? "2026-11-10" : ""}`.trim(),
    7.5,
    COLOR.dim
  );
  w.down(4);

  for (const r of rows) {
    w.ensure(100);
    w.textL(`${r.mpn} / ${r.description}`, 8.5, COLOR.ink, w.bold);
    w.textR(r.id, 7.5, COLOR.dim);
    w.down(6);
    w.hr(true);
    w.down(11);

    w.field("SUPPLIER OF RECORD", r.supplierOfRecord);
    w.field(`INTERMEDIATE PARENT / ${r.parentPct}%`, r.parentEntity);
    w.field(`ULTIMATE PARENT / CONF ${r.ultimateParentConf}%`, r.ultimateParent, COLOR.modeled);
    w.field(
      "AFFILIATES THRESHOLD",
      r.thresholdCrossed ? "50% CROSSED" : "BELOW 50%",
      r.thresholdCrossed ? COLOR.critical : COLOR.ink
    );
    w.down(4);
  }

  const srcIds = affiliateSourceIds(rows);
  w.paragraph(
    `SOURCES: ${OWNERSHIP_THRESHOLD_NOTE.sources} (${srcIds.join(", ")}). Ultimate-parent attribution is MODELED -- inferred from filings, not per-part observed.`,
    7.5,
    COLOR.dim
  );
}

// ---- footer -----------------------------------------------------------

function drawFooters(doc: PDFDocument, font: PDFFont, reviewLine: string) {
  const pages = doc.getPages();
  pages.forEach((p, i) => {
    p.drawLine({
      start: { x: MARGIN, y: MARGIN - 6 },
      end: { x: PAGE_W - MARGIN, y: MARGIN - 6 },
      thickness: 0.5,
      color: COLOR.rule,
    });

    // Row 1, directly under the hairline: review line (left) / page count
    // (right). Kept on its own row so it never shares a baseline with the
    // (possibly two-line) disclaimer below it -- sharing a row is what
    // caused the two to visually run together.
    const reviewClean = sanitizeForPdf(reviewLine);
    p.drawText(reviewClean, { x: MARGIN, y: MARGIN - 16, size: 6.5, font, color: COLOR.dim });

    const pageLabel = `PAGE ${i + 1} / ${pages.length}`;
    const pageW = font.widthOfTextAtSize(pageLabel, 6.5);
    p.drawText(pageLabel, {
      x: PAGE_W - MARGIN - pageW,
      y: MARGIN - 16,
      size: 6.5,
      font,
      color: COLOR.dim,
    });

    // Row 2+: the mandatory representative-data disclaimer, full width,
    // wrapped onto its own row(s) below the review line.
    const disclaimerLines = wrapText(font, 6.5, DISCLAIMER, CONTENT_W);
    let yy = MARGIN - 27;
    for (const line of disclaimerLines) {
      p.drawText(sanitizeForPdf(line), { x: MARGIN, y: yy, size: 6.5, font, color: COLOR.dim });
      yy -= 9;
    }
  });
}

// ---- main entry ---------------------------------------------------------

/**
 * Build the real, downloadable PDF for a RESOLVE action. Runs entirely
 * client-side (or in any Node runtime) via pdf-lib -- no headless
 * browser, so it is safe inside Vercel's function limits.
 */
export async function generateDocumentPdf(action: Action): Promise<Uint8Array> {
  const meta = DOC_META[action.kind];
  const lines = linesFor(action.id);
  const isLicense = action.kind === "LICENSE";

  const doc = await PDFDocument.create();
  doc.setTitle(`${DOC_TITLE[action.kind]} -- ${action.id}`);
  doc.setSubject("Gallium demo output -- representative data, fictional scenario");
  doc.setProducer("Gallium");
  doc.setCreator("Gallium");
  doc.setKeywords(["gallium", "demo", "representative", action.id]);

  const font = await doc.embedFont(StandardFonts.Courier);
  const bold = await doc.embedFont(StandardFonts.CourierBold);

  const w = new Writer(doc, font, bold);
  w.newPage();

  // ---- header ----
  w.row(ISSUER, meta.issuingDept, 8, COLOR.dim, bold);
  w.down(16);
  w.textL(DOC_TITLE[action.kind], 15, COLOR.ink, bold);
  w.textR("REPRESENTATIVE", 8, COLOR.focus, bold);
  w.down(14);
  w.hr(true);
  w.down(14);

  // ---- reference block ----
  w.row(`REF ${meta.refPrefix}-${ISSUE_DATE}`, `ISSUED ${ISSUE_DATE}`, 8, COLOR.dim);
  w.down(12);
  w.row(`${CUSTOMER.focusProduct.line} / ${CUSTOMER.location}`, action.id, 8, COLOR.dim);
  w.down(18);

  // ---- intro ----
  w.paragraph(DOC_INTRO[action.kind], 9.5, COLOR.secondary);
  w.down(6);

  // ---- line items / affiliates ----
  if (isLicense) {
    const rows = deriveAffiliateRows(lines);
    w.sectionLabel(meta.lineHeading, `${rows.length}`);
    drawAffiliatesTable(w, action, rows);
  } else {
    const { rows, subtotal, units, extendedTotal } = deriveLineItems(action, lines);
    w.sectionLabel(meta.lineHeading, `${rows.length}`);
    drawLineItemTable(w, action, rows, subtotal, units, extendedTotal);
  }
  w.down(4);

  // ---- parameters ----
  w.sectionLabel("PARAMETERS");
  for (const m of action.metrics) {
    w.field(m.label, m.note ? `${m.value}  (${m.note})` : m.value, m.warn ? COLOR.critical : COLOR.ink);
  }
  if (!isLicense) {
    w.field("OBSERVED RESOLVED", `${action.recovers} of ${OBSERVED_EXPOSED}`, COLOR.focus);
  }

  if (action.warning) {
    w.down(2);
    w.paragraph(`[!] ${action.warning}`, 8, COLOR.critical);
    w.down(2);
  }

  // ---- terms ----
  w.sectionLabel("TERMS");
  for (const t of meta.terms) {
    w.field(t.k, t.v);
  }

  // ---- authorization ----
  w.sectionLabel("AUTHORIZATION");
  const sigColW = CONTENT_W / 3;
  w.ensure(50);
  const sigY = w.y;
  meta.signatories.forEach((role, i) => {
    const x = MARGIN + i * sigColW;
    w.page.drawLine({
      start: { x, y: sigY },
      end: { x: x + sigColW - 16, y: sigY },
      thickness: 0.75,
      color: COLOR.ruleStrong,
    });
    w.page.drawText(sanitizeForPdf(role), { x, y: sigY - 11, size: 7.5, font: bold, color: COLOR.ink });
    w.page.drawText("SIGN / DATE", { x, y: sigY - 21, size: 7, font, color: COLOR.dim });
  });
  w.down(40);

  drawFooters(doc, font, meta.reviewLine);

  return doc.save();
}
